# Generated by Django 2.0.4 on 2018-04-30 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=200)),
                ('cinema_addr', models.CharField(max_length=200)),
                ('cinema_contact', models.CharField(max_length=20)),
                ('cinema_city', models.CharField(max_length=200)),
                ('cinema_state', models.CharField(max_length=2)),
                ('cinema_country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showing_time', models.DateTimeField(verbose_name='show time')),
                ('showing_date', models.DateTimeField(verbose_name='show date')),
                ('movie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_capacity', models.IntegerField(default=0)),
                ('cinema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.Cinema')),
            ],
        ),
        migrations.AddField(
            model_name='showing',
            name='theatre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation.Theatre'),
        ),
    ]
